### ISSUE TITLE
To-do list (alpha)

### ISSUE THREAD

**Issue by Polsaker** [Polsaker/shadowlamb#3]
* [ ] Connect to the IRC
 * [ ] Multi network
 * [ ] SSL
 * [ ] NickServ authentication (SASL)
 * [ ] Join channels
* [ ] Data storage (database)
 * [ ] Basic player storage
  * [ ] Stats
  * [ ] Inventory
  * [ ] Location
  * Leave room for spells and quests
* [ ] A modular way to add:
 * [ ] Cities
 * [ ] Places
  * [ ] Static NPCs
  * [ ] Dialogs
  * [ ] Requirements to enter (level, etc), probably with an event (to spawn guards?)
 * [ ] Dungeons
 * [ ] Items
 * [ ] Enemies/NPCs
